

@import {
	dl.Array
}

@build {
	Search = ("../libs")
	Link = ("chipmunk", "libglfw3.a", "libspine.a", "libstb.a")
	Debug = true
}


TypeInfo struct {
	size i32
}


Vec3 struct(T?, B?)  {
	x f32
	y f32
	z f32
}


Typed fn(type T?) {

}

Main fn() i32 {

   	i i32
   	f f32
   	array Array(i32)
   	Init(array, 10)

	return 1 + 5
}

Elements fn(array Array(T?)) T^
{
	return array.elements
}
Elements fn(array Array(T?), T^)
{
	return array.elements
}


// Control fn() {
// 	// if true
// 	// {

// 	// }
// 	// else if false
// 	// {

// 	// }
// 	// else {

// 	// }


// 	// for 0 .. 5 {

// 	// }

// 	// for false {

// 	// }

// 	// for (1, 2, 3) {

// 	// }
// }